name: Sync fork with upstream
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh repo sync ${{ github.repository }} --source Vidhin05/Releases-Regex
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
